version: 2.1

jobs:
  docker-job:
    docker:
      - image: cimg/aws:2024.03.1
    resource_class: medium
    steps:
      - run: sleep 60
  machine-job:
    machine: true
    resource_class: medium
    steps:
      - run: sleep 60

workflows:
  exec:
    jobs:
      - docker-job
      - machine-job
