version: 2.1

executors:
  default:
    machine: true
    resource_class: medium
  ubuntu-2204:
    machine:
      image: ubuntu-2204
    resource_class: medium
  ubuntu-2204-vm-nixos:
    machine:
      # alias
      image: vm-nixos
    resource_class: medium
      

jobs:
  machine-test:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - run: echo hello

workflows:
  vm-jobs:
    jobs:
      - machine-test:
          matrix:
            parameters:
              exec:
                - default
                - ubuntu-2204  # default
                - ubuntu-2204-vm-nixos
